### ISSUE TITLE
Issues with latest Doxgen

### ISSUE THREAD

**Issue by MrPeteypoo** [numb3r23/glslAdditions#1]
Hi there, I've been trying to use your filter to get doxygen output with my vertex and fragment shaders. I've followed your instructions and even tried your example and only get source code output, it doesn't generate the beautifully formatted documentation which I like doxygen for. Do you have any advice?

**Comment by numb3r23** [comment]
I have the same issue here with a recent doxygen version (1.8.9.1), while it's fine for the previously used 1.7.6.1. I'll investigate and then upload an example package

**Comment by numb3r23** [comment]
The issue can be resolved by adding the following configuration to doxygen:
`EXTENSION_MAPPING=.frag=C++, .vert=C++`
That way the output of the python parser is interpreted by doxygen's C++ parser which works. I've added an example to the repo you can run.

**Comment by MrPeteypoo** [comment]
Thanks a lot, I greatly appreciate the quick feedback, glad it's a simple fix!
